name: flutter_group_sliver
description: A new Flutter package project.
version: 0.0.2
author: mrdaios <mrdaios@gmail.com>
homepage: https://github.com/mrdaios/flutter_group_sliver

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter